keys:
  image2text: 'sk-xxx'
  selfcritic: 'sk-xxx'
  evaluation: 'sk-xxx'
  doubao: 'ep-xxx'
  deepseek: 'ep-xxx'
  ark: 'xxx'

data_paths:
  images: 'data/images'
  public_set: 'data/public_set.json'
  final_set: 'data/total.json'
  dev_set: 'data/dev_set.json'

output_paths:
  public_submit: 'results/public_submit'
  html_images: 'results/html_images_0624'
  generated_html_code: 'results/generated_html_code_0624'

logging:
  level: INFO

model: 
  type: 'deepseek'
